services:
  postgres:
    image: postgres:13.0-alpine
    container_name: test_postgres
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  db_value: